[build]
# This assumes the Zola site is in the docs folder.
base = "docs"
publish = "docs/public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.13.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"